from __future__ import annotations

from types import MappingProxyType


class EndpointAuthorizationContract:
    """Static authorization ownership for one Frappe-whitelisted endpoint."""

    CAPABILITY = "capability"
    DELEGATE = "delegate"
    FAIL_CLOSED = "fail_closed"
    SELF_CONTEXT = "self_context"


def _contracts(
    module: str,
    contract: str,
    *functions: str,
) -> dict[str, str]:
    return {f"{module}.{function}": contract for function in functions}


_CONTRACTS = {
    **_contracts(
        "almdina_erp.almdina_erp.api",
        EndpointAuthorizationContract.CAPABILITY,
        "get_approved_cutting_plan_snapshot",
        "preview_door_cutting_order",
    ),
    **_contracts(
        "almdina_erp.almdina_erp.doctype.door_cutting_order.door_cutting_order",
        EndpointAuthorizationContract.DELEGATE,
        "recalculate_order",
    ),
    **_contracts(
        "almdina_erp.almdina_erp.services.approval_queue_service",
        EndpointAuthorizationContract.CAPABILITY,
        "approve_order_safely",
        "get_approval_queue_context",
        "get_pending_review_orders",
        "reject_order_safely",
    ),
    **_contracts(
        "almdina_erp.almdina_erp.services.archive_service",
        EndpointAuthorizationContract.CAPABILITY,
        "archive_approved_plan_pdf",
        "get_archive_context",
    ),
    **_contracts(
        "almdina_erp.almdina_erp.services.cost_document_service",
        EndpointAuthorizationContract.CAPABILITY,
        "get_customer_invoice_document",
        "get_internal_cost_report_document",
    ),
    **_contracts(
        "almdina_erp.almdina_erp.services.cost_permission_service",
        EndpointAuthorizationContract.CAPABILITY,
        "approve_special_piece_price",
        "get_order_cost_snapshot",
        "update_clipped_corner_edge_price",
        "update_order_cost_settings",
    ),
    **_contracts(
        "almdina_erp.almdina_erp.services.cost_service",
        EndpointAuthorizationContract.CAPABILITY,
        "refresh_order_costs",
    ),
    **_contracts(
        "almdina_erp.almdina_erp.services.cutting_plan_service",
        EndpointAuthorizationContract.DELEGATE,
        "approve_order",
        "lock_cutting_plan",
        "reject_order",
        "send_order_to_production",
        "submit_order_for_review",
    ),
    **_contracts(
        "almdina_erp.almdina_erp.services.drawing_approval_service",
        EndpointAuthorizationContract.CAPABILITY,
        "approve_production_dxf",
    ),
    **_contracts(
        "almdina_erp.almdina_erp.services.dxf_export_service",
        EndpointAuthorizationContract.CAPABILITY,
        "get_validated_dxf_plan",
    ),
    **_contracts(
        "almdina_erp.almdina_erp.services.export_validation_service",
        EndpointAuthorizationContract.DELEGATE,
        "get_validated_dxf_plan",
    ),
    **_contracts(
        "almdina_erp.almdina_erp.services.legacy_endpoint_service",
        EndpointAuthorizationContract.DELEGATE,
        "cancel_legacy_replacement",
        "finish_legacy_stage",
        "start_legacy_stage",
    ),
    **_contracts(
        "almdina_erp.almdina_erp.services.legacy_endpoint_service",
        EndpointAuthorizationContract.FAIL_CLOSED,
        "retired_product_endpoint",
    ),
    **_contracts(
        "almdina_erp.almdina_erp.services.master_data_service",
        EndpointAuthorizationContract.CAPABILITY,
        "delete_master_data_record",
        "delete_production_routing",
        "get_master_data_console",
        "get_production_routing_console",
        "save_production_routing",
        "search_operational_roles",
        "set_master_data_disabled",
        "set_production_routing_disabled",
    ),
    **_contracts(
        "almdina_erp.almdina_erp.services.master_data_service",
        EndpointAuthorizationContract.SELF_CONTEXT,
        "can_open_master_data",
    ),
    **_contracts(
        "almdina_erp.almdina_erp.services.order_approval_service",
        EndpointAuthorizationContract.CAPABILITY,
        "approve_order",
    ),
    **_contracts(
        "almdina_erp.almdina_erp.services.order_cancellation",
        EndpointAuthorizationContract.CAPABILITY,
        "cancel_order",
    ),
    **_contracts(
        "almdina_erp.almdina_erp.services.order_defaults_service",
        EndpointAuthorizationContract.CAPABILITY,
        "get_order_defaults",
    ),
    **_contracts(
        "almdina_erp.almdina_erp.services.order_dispatch_service",
        EndpointAuthorizationContract.CAPABILITY,
        "dispatch_order",
        "validate_order_for_dispatch",
    ),
    **_contracts(
        "almdina_erp.almdina_erp.services.order_lifecycle_permission_service",
        EndpointAuthorizationContract.CAPABILITY,
        "get_order_lifecycle_context",
        "submit_order_for_review",
    ),
    **_contracts(
        "almdina_erp.almdina_erp.services.order_lifecycle_service",
        EndpointAuthorizationContract.CAPABILITY,
        "cancel_order",
        "return_order_to_draft",
    ),
    **_contracts(
        "almdina_erp.almdina_erp.services.order_plan_permission_service",
        EndpointAuthorizationContract.CAPABILITY,
        "recalculate_order",
        "simulate_optimizer_plan",
    ),
    **_contracts(
        "almdina_erp.almdina_erp.services.order_review_service",
        EndpointAuthorizationContract.CAPABILITY,
        "reject_order",
    ),
    **_contracts(
        "almdina_erp.almdina_erp.services.order_revision_service",
        EndpointAuthorizationContract.CAPABILITY,
        "create_order_revision",
        "return_order_to_draft",
    ),
    **_contracts(
        "almdina_erp.almdina_erp.services.permission_context_service",
        EndpointAuthorizationContract.SELF_CONTEXT,
        "get_permission_context",
    ),
    **_contracts(
        "almdina_erp.almdina_erp.services.permission_management_service",
        EndpointAuthorizationContract.CAPABILITY,
        "export_permission_bundle",
        "export_role_permissions",
        "get_permission_audit",
        "get_permission_console",
        "get_role_permissions",
        "import_permission_bundle",
        "preview_permission_bundle_import",
        "preview_permission_import",
        "preview_role_permissions",
        "update_role_permissions",
    ),
    **_contracts(
        "almdina_erp.almdina_erp.services.production_service",
        EndpointAuthorizationContract.DELEGATE,
        "finish_stage",
        "start_stage",
    ),
    **_contracts(
        "almdina_erp.almdina_erp.services.production_service",
        EndpointAuthorizationContract.FAIL_CLOSED,
        "pause_stage",
        "resume_stage",
    ),
    **_contracts(
        "almdina_erp.almdina_erp.services.production_settings_service",
        EndpointAuthorizationContract.CAPABILITY,
        "get_factory_settings_audit",
        "get_print_identity",
        "get_production_settings",
        "update_production_settings",
    ),
    **_contracts(
        "almdina_erp.almdina_erp.services.production_worker_service",
        EndpointAuthorizationContract.CAPABILITY,
        "get_reassignment_workers",
    ),
    **_contracts(
        "almdina_erp.almdina_erp.services.replacement_approval",
        EndpointAuthorizationContract.CAPABILITY,
        "approve_replacement",
    ),
    **_contracts(
        "almdina_erp.almdina_erp.services.replacement_completion",
        EndpointAuthorizationContract.CAPABILITY,
        "complete_replacement",
    ),
    **_contracts(
        "almdina_erp.almdina_erp.services.replacement_creation_service",
        EndpointAuthorizationContract.CAPABILITY,
        "create_replacement_from_incident",
        "record_incident",
    ),
    **_contracts(
        "almdina_erp.almdina_erp.services.replacement_execution",
        EndpointAuthorizationContract.CAPABILITY,
        "cancel_replacement",
        "start_replacement",
    ),
    **_contracts(
        "almdina_erp.almdina_erp.services.replacement_permission_service",
        EndpointAuthorizationContract.CAPABILITY,
        "get_replacement_context",
    ),
    **_contracts(
        "almdina_erp.almdina_erp.services.replacement_service",
        EndpointAuthorizationContract.DELEGATE,
        "approve_replacement",
        "cancel_replacement",
        "complete_replacement",
        "create_replacement_from_incident",
        "record_incident",
        "start_replacement",
    ),
    **_contracts(
        "almdina_erp.almdina_erp.services.report_permission_service",
        EndpointAuthorizationContract.CAPABILITY,
        "get_report_access_context",
    ),
    **_contracts(
        "almdina_erp.almdina_erp.services.shop_floor_commands",
        EndpointAuthorizationContract.CAPABILITY,
        "dispatch_order",
        "get_handoff_context",
        "get_handoff_workers",
        "handoff_to_next",
        "mark_delivered",
        "reassign_worker",
        "return_order_to_draft",
        "revert_department",
        "start_my_stage",
    ),
    **_contracts(
        "almdina_erp.almdina_erp.services.shop_floor_dxf_service",
        EndpointAuthorizationContract.CAPABILITY,
        "approve_production_dxf",
        "mark_dxf_exported",
        "recalculate_drawing_plan",
        "upload_production_dxf",
    ),
    **_contracts(
        "almdina_erp.almdina_erp.services.shop_floor_query_service",
        EndpointAuthorizationContract.CAPABILITY,
        "get_current_stage_context",
        "get_dispatch_options",
        "get_my_archive",
        "get_my_inbox",
        "get_order_operational_role_flags",
        "get_revert_targets",
        "get_shop_floor_context",
    ),
    **_contracts(
        "almdina_erp.almdina_erp.services.special_shape_service",
        EndpointAuthorizationContract.DELEGATE,
        "approve_special_piece_price",
    ),
    **_contracts(
        "almdina_erp.almdina_erp.services.workforce_service",
        EndpointAuthorizationContract.CAPABILITY,
        "adopt_workforce_user",
        "create_workforce_user",
        "get_workforce_console",
        "get_workforce_user_audit",
        "reset_workforce_password",
        "set_workforce_user_enabled",
        "update_workforce_user",
    ),
}

WHITELISTED_ENDPOINT_CONTRACTS = MappingProxyType(_CONTRACTS)


__all__ = [
    "EndpointAuthorizationContract",
    "WHITELISTED_ENDPOINT_CONTRACTS",
]
