"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const entry = fs.readFileSync(path.resolve(__dirname, "../../public/js/door_cutting_order/drawing/special_shape_facade.js"), "utf8");
const v4Bootstrap = fs.readFileSync(path.resolve(__dirname, "../../public/js/door_drawing_v4/bootstrap.js"), "utf8");
const geometry = fs.readFileSync(path.resolve(__dirname, "../../public/js/door_drawing_v3/domain/geometry.js"), "utf8");
const smartPathDomain = fs.readFileSync(path.resolve(__dirname, "../../public/js/door_drawing_v3/domain/smart_path_domain.js"), "utf8");
const smartPathPersistence = fs.readFileSync(path.resolve(__dirname, "../../public/js/door_drawing_v3/infrastructure/smart_path_persistence.js"), "utf8");
const snapping = fs.readFileSync(path.resolve(__dirname, "../../public/js/door_drawing_v3/application/snapping.js"), "utf8");
const smartPathSnapping = fs.readFileSync(path.resolve(__dirname, "../../public/js/door_drawing_v3/application/smart_path_snapping.js"), "utf8");
const moveSnapPolicy = fs.readFileSync(path.resolve(__dirname, "../../public/js/door_drawing_v3/application/move_snap_policy.js"), "utf8");
const smartGuides = fs.readFileSync(path.resolve(__dirname, "../../public/js/door_drawing_v3/application/smart_guides.js"), "utf8");
const handles = fs.readFileSync(path.resolve(__dirname, "../../public/js/door_drawing_v3/application/shape_handles.js"), "utf8");
const precision = fs.readFileSync(path.resolve(__dirname, "../../public/js/door_drawing_v3/application/precision_input.js"), "utf8");
const freehand = fs.readFileSync(path.resolve(__dirname, "../../public/js/door_drawing_v3/application/smart_freehand_policy.js"), "utf8");
const intelligence = fs.readFileSync(path.resolve(__dirname, "../../public/js/door_drawing_v3/application/smart_stroke_intelligence.js"), "utf8");
const view = fs.readFileSync(path.resolve(__dirname, "../../public/js/door_drawing_v3/presentation/canvas_view.js"), "utf8");
const smartPathView = fs.readFileSync(path.resolve(__dirname, "../../public/js/door_drawing_v3/presentation/smart_path_view.js"), "utf8");
const smartGuidesView = fs.readFileSync(path.resolve(__dirname, "../../public/js/door_drawing_v3/presentation/smart_guides_view.js"), "utf8");
const editor = fs.readFileSync(path.resolve(__dirname, "../../public/js/door_drawing_v3/application/editor_stage2.js"), "utf8");
const magnetic = fs.readFileSync(path.resolve(__dirname, "../../public/js/door_drawing_v3/application/magnetic_connection.js"), "utf8");
const smartPen = fs.readFileSync(path.resolve(__dirname, "../../public/js/door_drawing_v3/application/smart_pen.js"), "utf8");
const css = fs.readFileSync(path.resolve(__dirname, "../../public/css/door_drawing_v3.css"), "utf8");
const precisionCss = fs.readFileSync(path.resolve(__dirname, "../../public/css/door_drawing_v3_precision.css"), "utf8");
const magneticCss = fs.readFileSync(path.resolve(__dirname, "../../public/css/door_drawing_v3_magnetic.css"), "utf8");
const smartPenCss = fs.readFileSync(path.resolve(__dirname, "../../public/css/door_drawing_v3_smart_pen.css"), "utf8");
const smartGuidesCss = fs.readFileSync(path.resolve(__dirname, "../../public/css/door_drawing_v3_smart_guides.css"), "utf8");

// V3 remains covered as an isolated legacy subsystem, but it no longer owns the
// public special-shape facade. The active facade delegates V4 module ownership to
// the centralized bootstrap so stale V3 assumptions cannot become runtime dependencies.
assert.match(entry, /door_drawing_v4\/bootstrap\.js/);
assert.match(v4Bootstrap, /door_drawing_v4\/domain\/geometry\.js/);
assert.match(v4Bootstrap, /door_drawing_v4\/presentation\/editor_controller\.js/);
assert.match(entry, /__doorDrawingV4:\s*true/);
assert.doesNotMatch(entry, /door_drawing_v3\//);
assert.doesNotMatch(v4Bootstrap, /door_drawing_v3\//);
assert.doesNotMatch(entry, /__doorDrawingV3/);
assert.doesNotMatch(entry, /AlmdinaSketchEngine|AlmdinaExactLineModel|AlmdinaSketchHistory/);

for (const tool of ["line", "rectangle", "circle", "arc"]) assert.match(view, new RegExp(`data-ddv3-tool=\\"${tool}\\"`));
assert.match(view, /field\("Length",\s*"length"/);
assert.match(view, /field\("Radius",\s*"radius"/);
assert.match(view, /field\("Sweep",\s*"sweep"/);
assert.match(view, /function arcPath/);
assert.match(view, /function snapMarkup/);
assert.match(view, /function handlesMarkup/);
assert.match(view, /data-ddv3-handle/);
assert.match(view, /function displayObject/);
assert.match(view, /ddv3-snap-indicator/);
assert.match(view, /Ctrl\+Shift\+Z/);

assert.match(editor, /function handleArcClick/);
assert.match(editor, /function handleCandidate/);
assert.match(editor, /function updatePrecisionPreview/);
assert.match(editor, /function commitPrecision/);
assert.match(editor, /function handlePrecisionKey/);
assert.match(editor, /clickDraft/);
assert.match(editor, /Precision\.lineFromInput/);
assert.match(editor, /Precision\.rectangleFromInput/);
assert.match(editor, /Precision\.circleFromInput/);
assert.match(editor, /Precision\.arcFromSweep/);
assert.match(editor, /Handles\.resize/);
assert.match(editor, /S\.resolvePoint/);
assert.match(editor, /S\.resolveArcEndpoint/);
assert.match(editor, /forcedAxis:/);
assert.match(editor, /axisLock:\s*c\.tool === "line"/);
assert.match(editor, /G\.translateObject/);
assert.match(editor, /root\.EditorStage5/);
assert.match(editor, /r:\s*"rectangle"/);
assert.match(editor, /o:\s*"circle"/);
assert.match(editor, /a:\s*"arc"/);

assert.match(geometry, /function rectangle\(/);
assert.match(geometry, /function circle\(/);
assert.match(geometry, /function arc\(/);
assert.match(smartPathDomain, /const PATH_TYPE = "path"/);
assert.match(smartPathDomain, /function path\(/);
assert.match(smartPathDomain, /function pathSegments\(/);
assert.match(smartPathDomain, /function insertPathPoint\(/);
assert.match(smartPathDomain, /function removePathPoint\(/);
assert.match(smartPathDomain, /function nearestPathSegment\(/);
assert.doesNotMatch(smartPathDomain, /window\.document|document\.querySelector|document\.createElement|getBoundingClientRect|clientX|clientY/, "Smart path geometry must remain independent from browser DOM coordinates");
assert.match(smartPathPersistence, /object\.type === G\.PATH_TYPE/);
assert.match(smartPathPersistence, /authoritative:\s*"door_drawing_v3"/);

assert.match(snapping, /const DEFAULT_SNAP_PX = 22/);
assert.match(snapping, /const JOIN_SNAP_PX = 26/);
assert.match(snapping, /function objectAnchors/);
assert.match(snapping, /function preferredAnchor/);
assert.match(snapping, /function resolvePoint/);
assert.match(snapping, /function resolveObjectMove/);
assert.match(snapping, /forcedAxis/);
assert.match(smartPathSnapping, /function pathAnchors/);
assert.match(smartPathSnapping, /role:\s*`node-\$\{index\}`/);
assert.match(smartPathSnapping, /function resolveObjectMove/);
assert.match(moveSnapPolicy, /const EASY_MOVE_JOIN_SNAP_PX = 20/);
assert.match(smartGuides, /const SURFACE_SNAP_PX = 14/);
assert.match(smartGuides, /const ALIGN_SNAP_PX = 9/);
assert.match(smartGuides, /function nearestSurface/);
assert.match(smartGuides, /function anchorAlignment/);
assert.match(smartGuides, /function equalLengthCandidate/);
assert.match(smartGuides, /kind: "surface"/);
assert.match(smartGuides, /kind: "alignment"/);
assert.match(smartGuides, /kind: "equal-length"/);
assert.doesNotMatch(snapping + smartPathSnapping + moveSnapPolicy + smartGuides, /clientX|clientY|getBoundingClientRect/, "Snapping application policy must stay independent from DOM coordinates");

assert.match(handles, /function handlesFor/);
assert.match(handles, /function resizeRectangle/);
assert.match(handles, /function resizeCircle/);
assert.match(handles, /function resizeArc/);
assert.doesNotMatch(handles, /document\.|querySelector|getBoundingClientRect|clientX|clientY/, "Shape handle transforms must remain independent from DOM coordinates");
assert.match(precision, /function parseLine/);
assert.match(precision, /function parseRectangle/);
assert.match(precision, /function parseCircle/);
assert.match(precision, /function parseArc/);
assert.doesNotMatch(precision, /document\.|querySelector|getBoundingClientRect|clientX|clientY|px\b/i, "Precision input must remain a world-mm application policy, not a screen coordinate feature");
assert.match(freehand, /function appendSample/);
assert.match(freehand, /function simplifyRdp/);
assert.match(freehand, /function lineQuality/);
assert.match(freehand, /function fittedCircle/);
assert.match(freehand, /function unwrapSweep/);
assert.match(freehand, /function recognize/);
assert.doesNotMatch(freehand, /document\.|querySelector|getBoundingClientRect|clientX|clientY|pointerId/, "Freehand correction must remain geometry/application policy, independent from DOM/pointer events");
assert.match(intelligence, /function createStabilizer/);
assert.match(intelligence, /function pushStabilized/);
assert.match(intelligence, /function arcThroughEndpoints/);
assert.match(intelligence, /function recognizeMixed/);
assert.match(intelligence, /function interpret/);
assert.doesNotMatch(intelligence, /document\.|querySelector|getBoundingClientRect|clientX|clientY|pointerId/, "Stroke intelligence must remain independent from DOM and pointer-event coordinates");

assert.match(magnetic, /function magneticMove/);
assert.match(magnetic, /S\.resolveObjectMove/);
assert.match(magnetic, /function hoverSnap/);
assert.match(magnetic, /stickyTarget/);
assert.match(smartPathView, /dataset\.ddv3Tool = "pen"/);
assert.match(smartPathView, /data-ddv3-path-node/);
assert.match(smartPathView, /data-ddv3-path-segment/);
assert.match(smartPathView, /is-freehand/);
assert.match(smartPathView, /function renderPathInspector/);
assert.match(smartGuidesView, /function guideMarkup/);
assert.match(smartGuidesView, /horizontal-alignment/);
assert.match(smartGuidesView, /vertical-alignment/);
assert.match(smartGuidesView, /equal-length/);
assert.match(smartPen, /const CLOSE_CAPTURE_PX = 8/);
assert.match(smartPen, /const FREEHAND_ENDPOINT_SNAP_PX = 8/);
assert.match(smartPen, /snapPx:\s*FREEHAND_ENDPOINT_SNAP_PX/);
assert.match(smartPen, /function beginFreehand/);
assert.match(smartPen, /function moveFreehand/);
assert.match(smartPen, /function finishFreehand/);
assert.match(smartPen, /getCoalescedEvents/);
assert.match(smartPen, /F\.appendSample/);
assert.match(smartPen, /I\.pushStabilized/);
assert.match(smartPen, /I\.interpret/);
assert.match(smartPen, /function objectsFromRecognition/);
assert.match(smartPen, /Smart mixed stroke/);
assert.match(smartPen, /function enterNodeEdit/);
assert.match(smartPen, /function insertNodeAtEvent/);
assert.match(smartPen, /G\.setPathPoint/);
assert.match(smartPen, /G\.removePathPoint/);
assert.doesNotMatch(smartPen, /Math\.round\(angle \/ 45\) \* 45|event\.detail >= 2/, "The pen must be freehand, not click-to-place polygon drafting");
assert.doesNotMatch(editor + view + magnetic + smartPen + smartPathView + smartGuidesView, /special_shape_geometry_json\s*=/, "Drawing editor must not fabricate manufacturing geometry from visual output");

assert.match(css, /\.ddv3-app/);
assert.match(css, /\.ddv3-inspector/);
assert.match(css, /\.ddv3-toolbar/);
assert.match(css, /\.ddv3-measure/);
assert.match(css, /\.ddv3-handle/);
assert.match(css, /\.ddv3-snap-axis-guide/);
assert.match(css, /\.ddv3-snap-indicator/);
assert.match(precisionCss, /\.ddv3-precision-entry/);
assert.match(magneticCss, /\.ddv3-magnetic-badge/);
assert.match(magneticCss, /has-magnetic-snap/);
assert.match(smartPenCss, /\.ddv3-path-stroke/);
assert.match(smartPenCss, /\.ddv3-path-node/);
assert.match(smartPenCss, /\.ddv3-pen-draft\.is-freehand/);
assert.match(smartPenCss, /\.ddv3-freehand-tip/);
assert.match(smartGuidesCss, /\.ddv3-smart-guide/);
assert.match(smartGuidesCss, /\.ddv3-smart-guide-surface/);
assert.doesNotMatch(css + precisionCss + magneticCss + smartPenCss + smartGuidesCss, /^body\s*\{/m);
assert.doesNotMatch(css + precisionCss + magneticCss + smartPenCss + smartGuidesCss, /^\.form-layout\s*\{/m);

console.log("Door Drawing V3 legacy subsystem architecture contract passed; active facade remains V4");
